name: Deploy to Dev

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.base.ref == 'develop' && github.event.pull_request.head.ref != 'develop' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyyaml
          pip install -r requirements.txt

      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev environment"
          python scripts/pre_checks.py 
          # Add your deployment steps here
