name: Deploy to Dev

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.base.ref == 'develop' && contains(github.event.pull_request.head.ref, 'feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: '3.x'  # Choose the Python version you want to use

      - name: Install dependencies
        run: pip install pyyaml
      
     #- name: Install AWS CLI
       # run: |
        #  sudo apt-get update
         # sudo apt-get install -y awscli
      
      #- name: Configure AWS credentials
       # run: |
        #  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
         # aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Deploy to Dev
        # Add your deployment steps here
        run: |
          echo "Deploying to Dev environment"
          pip install -r requirements.txt  # If you have any dependencies, specify them in requirements.txt
          python scripts/pre_checks.py 
        #  aws s3 sync sql/ s3://your-dev-bucket/sql/
      
      #- name: Check if PR closed for develop to test
       # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'test' && github.event.pull_request.merged == true
        #run: |
         # aws s3 sync sql/ s3://your-test-bucket/sql/
