name: Deploy to S3

on:
  push:
    branches:
      - develop
      
 # pull_request:
  #  types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region eu-west-2
      
      - name: Check if PR merged to develop
       # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'develop' && github.event.pull_request.merged == true
        run: |
          aws s3 cp datamigration/ s3://mysamplebuckethello/ --resursive
