name: Pre-checks

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  pre-checks:
    name: Pre-checks
    runs-on: ubuntu-latest

    env:
      INPUT_DIRECTORY: 'datamigration'  # Adjust this to your directory path
      INPUT_PREFIX: 'pre_'  # Adjust this to your prefix

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose the Python version you want to use

    - name: Install dependencies
      run: pip install pyyaml
      
    - name: Run pre-checks
      run: |
        pip install -r requirements.txt  # If you have any dependencies, specify them in requirements.txt
        python pre_checks.py
        
    - name: Run sql-pre-checks
      run: |
        pip install -r requirements.txt  # If you have any dependencies, specify them in requirements.txt
        python sql-pre-check-stg.py
