name: Pre-checks

on:
  push:
    branches:
      - develop  # Change this to your main branch name

jobs:
  pre-checks:
    name: Pre-checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose the Python version you want to use

    - name: Install dependencies
      run: pip install pyyaml
      
    - name: Run pre-checks
      run: |
        pip install -r requirements.txt  # If you have any dependencies, specify them in requirements.txt
        python pre_checks.py
        
   # - name: Run sql-pre-checks-stg-trn
   #   run: |
   #     pip install -r requirements.txt  # If you have any dependencies, specify them in requirements.txt
   #     python sql-pre-check-stg-trn.py

   # - name: Run sql-pre-checks-ext
   #   run: |
   #     pip install -r requirements.txt  # If you have any dependencies, specify them in requirements.txt
   #     python sql-pre-check-ext.py
        
   # - name: Run pre-checks-for-python
   #   run: |
   #     pip install -r requirements.txt  # If you have any dependencies, specify them in requirements.txt
   #     python pre-check-for-python-files.py   
